### ISSUE TITLE
通过 LiteLoaderQQNT 修改 QQ 的字体

### ISSUE THREAD

**Issue by ApliNi** [ApliNi/blog#15]
0. 安装 [QQNT](https://im.qq.com/pcqq/index.shtml)
1. 安装 [LiteLoaderQQNT](https://github.com/mo-jinran/LiteLoaderQQNT)
2. 在设置中安装 [LiteLoaderQQNT-Custom-CSS](https://github.com/xh321/LiteLoaderQQNT-Custom-CSS) 插件
3. 打开文件 `<用户目录>/Documents/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Custom-CSS-master/style.css`
4. 往里面粘贴代码: 
```css
/* 修改字体 */
@font-face {
	font-family: 'HarmonyOS';
	font-display: swap;
	/* 这里可以是任何本地路径, 但需要添加 `llqqnt://local-file/` 前缀 */
	src: url('llqqnt://local-file/C:/Users/<用户名>/AppData/Local/Microsoft/Windows/Fonts/HarmonyOS_Sans_SC_Regular_1.ttf');
}
body {
	/* 优先使用 Trebuchet MS 字体, 然后是在上方定义的 HarmonyOS */
	font-family: 'Trebuchet MS', 'HarmonyOS' !important;
}

```
